### ISSUE TITLE
Stop server issue

### ISSUE THREAD

**Issue by MangyCat** [Enderbyte-Programs/CraftServerSetup#1]
When i type in stop into the minecraft command line, it stalls till i have to press CTRL+C on my  keyboard so minecraft could forcibly be stopped and then get an error message  saying Your minecraft server crashed! Wanna view the logs? even though i stopped the server manually.

OS: arch linux, using spigot server type, without activated product key.

idea: the UI is very nice and accomodating for an text terminal. Why not make it an web interface instead so that we arent limited by text and could have sliders, radio buttons, boxes, pictures and much more, it would be very useful for controlling the program and we could also add password protection if we wish, and the program wouldnt feel gloomy and black and white except for the occassional red and green in the setup stage. the server setup without issues. that was the issue i could find so far.

**Comment by MangyCat** [comment]
Oh yeah and another issue, while the advertisment popped up i clicked yes and the link opened succussfully but the massive issue was that the logs from the browser were somehow flowing into the terminal and messing with the interface, so make it so the logs dont show up by probably making it forward the logs to /dev/null ?
and in the web interface idea we could also add other peoples ads to the side of the webpage and not relying on 20 percent chance so the ad pops up whilst navigating.
![Screenshot_2023-09-30_18-32-57](https://github.com/Enderbyte-Programs/CraftServerSetup/assets/73955445/faed1f40-be17-4d57-8422-43f030281b3a)

**Comment by Enderbyte09** [comment]
Thank you for leaving a bug report. May I ask if you were running this within a desktop environment or on a TTY?
Also for some reason _lavacat is not valid Discord username so your product key is 12120223

**Comment by Enderbyte09** [comment]
Also, what browser were you using?

**Comment by Enderbyte09** [comment]
> t stalls till i have to press CTRL+C on my keyboard so minecraft could forcibly be stopped

Apologies for the excessive comments but:
-What plugins?
-Did the process finish?
-What version?

**Comment by Enderbyte09** [comment]
This is likely a problem with Spigot. However, I will try to have the "Your server crashed" warning not trigger if you do ctrl-c.
