### ISSUE TITLE
Bug while messing around on codespaces

### ISSUE THREAD

**Issue by StephenR18** [Enderbyte-Programs/CraftServerSetup#40]
I received a lot of this type of errors while trying to install it on codespaces, I guess is some problem related with the version of Python XD

This one ocurred while trying to enter the "change MOTD" option

![Captura de pantalla 2024-06-24 151420](https://github.com/Enderbyte-Programs/CraftServerSetup/assets/173580857/f8cd46b9-ef6c-4587-b912-fed4a5d4208d)

**Comment by Enderbyte09** [comment]
Are you trying to install an extremely old version of Minecraft?

**Comment by StephenR18** [comment]
> Are you trying to install an extremely old version of Minecraft?

Nope, it's spigot 1.20.2

**Comment by StephenR18** [comment]
Nope, im gonna try that now

**Comment by Enderbyte09** [comment]
I was unable to replicate it on my computer, but you have brought up a good point about nonstandard config files if they exist. A patch will be released in approximately one minute as v1.40.4.

**Comment by StephenR18** [comment]
> I was unable to replicate it on my computer, but you have brought up a good point about nonstandard config files if they exist. A patch will be released in approximately one minute as v1.40.4.

The bug did not came out again after starting the server. 
I don't know if it was clear but I'm trying to run this on github codespaces

**Comment by Enderbyte09** [comment]
Codespaces shouldn't create a difference unless it's blocking file writes. Oh well, version 1.40.4 (which has already been released) has fixed this issue.

If you can confirm it works now, I'll go and close this issue.

Thank you for filing a bug report. Bug reports greatly improve the software!

**Comment by StephenR18** [comment]
Sure, I'll let you know if i find another bug
